# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 480)
        MainWindow.setWindowOpacity(0.9)
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(68, 68, 68);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_task = QtWidgets.QPushButton(self.frame_1)
        self.pushButton_task.setStyleSheet("background-color: rgb(89, 153, 59);")
        self.pushButton_task.setObjectName("pushButton_task")
        self.horizontalLayout_3.addWidget(self.pushButton_task)
        self.pushButton_course = QtWidgets.QPushButton(self.frame_1)
        self.pushButton_course.setStyleSheet("background-color: rgb(89, 153, 59);")
        self.pushButton_course.setObjectName("pushButton_course")
        self.horizontalLayout_3.addWidget(self.pushButton_course)
        self.pushButton_dial_a_mentor = QtWidgets.QPushButton(self.frame_1)
        self.pushButton_dial_a_mentor.setStyleSheet("background-color: rgb(89, 153, 59);")
        self.pushButton_dial_a_mentor.setObjectName("pushButton_dial_a_mentor")
        self.horizontalLayout_3.addWidget(self.pushButton_dial_a_mentor)
        self.verticalLayout_2.addWidget(self.frame_1)
        self.splitter_main_frames = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_main_frames.setOrientation(QtCore.Qt.Vertical)
        self.splitter_main_frames.setObjectName("splitter_main_frames")
        self.frame_2 = QtWidgets.QFrame(self.splitter_main_frames)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame_2_1 = QtWidgets.QFrame(self.splitter)
        self.frame_2_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_1.setObjectName("frame_2_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_search = QtWidgets.QLineEdit(self.frame_2_1)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.verticalLayout.addWidget(self.lineEdit_search)
        self.pushButton_search = QtWidgets.QPushButton(self.frame_2_1)
        self.pushButton_search.setStyleSheet("background-color: rgb(121, 255, 97);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_search.setObjectName("pushButton_search")
        self.verticalLayout.addWidget(self.pushButton_search)
        self.textEdit_search_result = QtWidgets.QTextEdit(self.frame_2_1)
        self.textEdit_search_result.setObjectName("textEdit_search_result")
        self.verticalLayout.addWidget(self.textEdit_search_result)
        self.frame_2_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_2.setObjectName("frame_2_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_result_display = QtWidgets.QTextEdit(self.frame_2_2)
        self.textEdit_result_display.setObjectName("textEdit_result_display")
        self.horizontalLayout.addWidget(self.textEdit_result_display)
        self.frame_2_3 = QtWidgets.QFrame(self.splitter)
        self.frame_2_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_3.setObjectName("frame_2_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_media_player = QtWidgets.QTextEdit(self.frame_2_3)
        self.textEdit_media_player.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.textEdit_media_player.setObjectName("textEdit_media_player")
        self.horizontalLayout_2.addWidget(self.textEdit_media_player)
        self.horizontalLayout_5.addWidget(self.splitter)
        self.frame_3 = QtWidgets.QFrame(self.splitter_main_frames)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter_2 = QtWidgets.QSplitter(self.frame_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_3_1 = QtWidgets.QFrame(self.splitter_2)
        self.frame_3_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3_1.setObjectName("frame_3_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3_1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_note = QtWidgets.QLabel(self.frame_3_1)
        self.label_note.setObjectName("label_note")
        self.verticalLayout_3.addWidget(self.label_note)
        self.plainTextEdit_note = QtWidgets.QPlainTextEdit(self.frame_3_1)
        self.plainTextEdit_note.setObjectName("plainTextEdit_note")
        self.verticalLayout_3.addWidget(self.plainTextEdit_note)
        self.pushButton_note = QtWidgets.QPushButton(self.frame_3_1)
        self.pushButton_note.setStyleSheet("background-color: rgb(121, 255, 97);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_note.setObjectName("pushButton_note")
        self.verticalLayout_3.addWidget(self.pushButton_note)
        self.frame_3_2 = QtWidgets.QFrame(self.splitter_2)
        self.frame_3_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3_2.setObjectName("frame_3_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit_note_display = QtWidgets.QTextEdit(self.frame_3_2)
        self.textEdit_note_display.setObjectName("textEdit_note_display")
        self.verticalLayout_4.addWidget(self.textEdit_note_display)
        self.frame_3_3 = QtWidgets.QFrame(self.splitter_2)
        self.frame_3_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3_3.setObjectName("frame_3_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textEdit_list_note = QtWidgets.QTextEdit(self.frame_3_3)
        self.textEdit_list_note.setObjectName("textEdit_list_note")
        self.verticalLayout_5.addWidget(self.textEdit_list_note)
        self.horizontalLayout_4.addWidget(self.splitter_2)
        self.verticalLayout_2.addWidget(self.splitter_main_frames)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 653, 21))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        self.menuPseudo = QtWidgets.QMenu(self.menubar)
        self.menuPseudo.setObjectName("menuPseudo")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuPseudo.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_task.setText(_translate("MainWindow", "Tasks"))
        self.pushButton_course.setText(_translate("MainWindow", "Courses"))
        self.pushButton_dial_a_mentor.setText(_translate("MainWindow", "Dial a Mentor"))
        self.lineEdit_search.setPlaceholderText(_translate("MainWindow", "search by name or keyword"))
        self.pushButton_search.setText(_translate("MainWindow", "Search"))
        self.label_note.setText(_translate("MainWindow", "NOTES"))
        self.plainTextEdit_note.setPlaceholderText(_translate("MainWindow", "Edit your notes here..."))
        self.pushButton_note.setText(_translate("MainWindow", "Save"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.menuPseudo.setTitle(_translate("MainWindow", "Pseudo"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
