# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(378, 558)
        Frame.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.register_btn = QtWidgets.QPushButton(Frame)
        self.register_btn.setGeometry(QtCore.QRect(70, 420, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.register_btn.setFont(font)
        self.register_btn.setMouseTracking(True)
        self.register_btn.setStyleSheet("background-color: rgb(121, 255, 97);")
        self.register_btn.setCheckable(True)
        self.register_btn.setObjectName("register_btn")
        self.password = QtWidgets.QLineEdit(Frame)
        self.password.setGeometry(QtCore.QRect(70, 330, 231, 31))
        self.password.setAutoFillBackground(False)
        self.password.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(130, 130, 130);")
        self.password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password.setText("")
        self.password.setMaxLength(50)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(False)
        self.password.setObjectName("password")
        self.register_label = QtWidgets.QLabel(Frame)
        self.register_label.setEnabled(True)
        self.register_label.setGeometry(QtCore.QRect(50, 120, 181, 20))
        self.register_label.setAutoFillBackground(False)
        self.register_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.register_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.register_label.setLineWidth(1)
        self.register_label.setMidLineWidth(0)
        self.register_label.setTextFormat(QtCore.Qt.RichText)
        self.register_label.setScaledContents(False)
        self.register_label.setOpenExternalLinks(False)
        self.register_label.setObjectName("register_label")
        self.signup_label = QtWidgets.QLabel(Frame)
        self.signup_label.setGeometry(QtCore.QRect(140, 80, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.signup_label.setFont(font)
        self.signup_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.signup_label.setObjectName("signup_label")
        self.ca_brand = QtWidgets.QLabel(Frame)
        self.ca_brand.setEnabled(True)
        self.ca_brand.setGeometry(QtCore.QRect(80, 40, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ca_brand.setFont(font)
        self.ca_brand.setAutoFillBackground(False)
        self.ca_brand.setStyleSheet("color: rgb(255, 255, 255);")
        self.ca_brand.setObjectName("ca_brand")
        self.name_field = QtWidgets.QLineEdit(Frame)
        self.name_field.setGeometry(QtCore.QRect(70, 170, 231, 31))
        self.name_field.setAutoFillBackground(False)
        self.name_field.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(130, 130, 130);")
        self.name_field.setInputMethodHints(QtCore.Qt.ImhNone)
        self.name_field.setText("")
        self.name_field.setMaxLength(20)
        self.name_field.setObjectName("name_field")
        self.contact_link = QtWidgets.QCommandLinkButton(Frame)
        self.contact_link.setGeometry(QtCore.QRect(230, 110, 101, 41))
        self.contact_link.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(189, 189, 189);")
        self.contact_link.setIconSize(QtCore.QSize(20, 20))
        self.contact_link.setCheckable(False)
        self.contact_link.setChecked(False)
        self.contact_link.setObjectName("contact_link")
        self.password_field = QtWidgets.QLineEdit(Frame)
        self.password_field.setGeometry(QtCore.QRect(70, 290, 231, 31))
        self.password_field.setAutoFillBackground(False)
        self.password_field.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(130, 130, 130);")
        self.password_field.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_field.setText("")
        self.password_field.setMaxLength(50)
        self.password_field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_field.setClearButtonEnabled(False)
        self.password_field.setObjectName("password_field")
        self.phone_field = QtWidgets.QLineEdit(Frame)
        self.phone_field.setGeometry(QtCore.QRect(70, 250, 231, 31))
        self.phone_field.setAutoFillBackground(False)
        self.phone_field.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(130, 130, 130);")
        self.phone_field.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.phone_field.setText("")
        self.phone_field.setMaxLength(50)
        self.phone_field.setClearButtonEnabled(False)
        self.phone_field.setObjectName("phone_field")
        self.email_field = QtWidgets.QLineEdit(Frame)
        self.email_field.setGeometry(QtCore.QRect(70, 210, 231, 31))
        self.email_field.setAutoFillBackground(False)
        self.email_field.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(130, 130, 130);")
        self.email_field.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhSensitiveData)
        self.email_field.setText("")
        self.email_field.setMaxLength(50)
        self.email_field.setClearButtonEnabled(False)
        self.email_field.setObjectName("email_field")
        self.male_check = QtWidgets.QRadioButton(Frame)
        self.male_check.setGeometry(QtCore.QRect(70, 371, 82, 17))
        self.male_check.setStyleSheet("color: rgb(255, 255, 255);")
        self.male_check.setObjectName("male_check")
        self.female_check = QtWidgets.QRadioButton(Frame)
        self.female_check.setGeometry(QtCore.QRect(170, 370, 82, 20))
        self.female_check.setStyleSheet("color: rgb(255, 255, 255);")
        self.female_check.setObjectName("female_check")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.register_btn.setText(_translate("Frame", "Register"))
        self.password.setPlaceholderText(_translate("Frame", "Confirm Password*"))
        self.register_label.setText(_translate("Frame", "Having Trouble to Register or log in?"))
        self.signup_label.setText(_translate("Frame", "Sign up"))
        self.ca_brand.setText(_translate("Frame", "CODE ASSISTANT"))
        self.name_field.setPlaceholderText(_translate("Frame", "Username*"))
        self.contact_link.setText(_translate("Frame", "Contac us"))
        self.password_field.setPlaceholderText(_translate("Frame", "Password*"))
        self.phone_field.setPlaceholderText(_translate("Frame", "Phone number"))
        self.email_field.setPlaceholderText(_translate("Frame", "Email*"))
        self.male_check.setText(_translate("Frame", "Male"))
        self.female_check.setText(_translate("Frame", "Female"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
